version: 1
directus: 9.22.1
collections:
  - collection: articles
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: status
      archive_value: archived
      collapse: open
      collection: articles
      color: '#6644FF'
      display_template: '{{status}}'
      group: null
      hidden: false
      icon: article
      item_duplication_fields: null
      note: Blog post articles written by our team
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: draft
    schema:
      collation: utf8mb4_0900_ai_ci
      comment: ''
      engine: InnoDB
      name: articles
      schema: coolstack_dev
fields:
  - collection: articles
    field: author
    meta:
      collection: articles
      conditions: null
      display: null
      display_options: null
      field: author
      group: null
      hidden: false
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar.$thumbnail}}{{first_name}}{{last_name}}'
      readonly: true
      required: false
      sort: null
      special:
        - m2o
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: char
      default_value: null
      foreign_key_column: id
      foreign_key_table: directus_users
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 36
      name: author
      numeric_precision: null
      numeric_scale: null
      table: articles
    type: string
  - collection: articles
    field: body
    meta:
      collection: articles
      conditions: null
      display: null
      display_options: null
      field: body
      group: null
      hidden: false
      interface: input-rich-text-html
      note: null
      options:
        toolbar:
          - aligncenter
          - alignjustify
          - alignleft
          - alignnone
          - alignright
          - backcolor
          - blockquote
          - bold
          - bullist
          - code
          - copy
          - customImage
          - customLink
          - customMedia
          - cut
          - fontselect
          - fontsizeselect
          - forecolor
          - fullscreen
          - h1
          - h2
          - h3
          - h4
          - h5
          - h6
          - hr
          - indent
          - italic
          - ltr rtl
          - numlist
          - outdent
          - paste
          - redo
          - remove
          - removeformat
          - selectall
          - strikethrough
          - subscript
          - superscript
          - table
          - underline
          - undo
          - unlink
          - visualaid
      readonly: false
      required: false
      sort: 6
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: text
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 65535
      name: body
      numeric_precision: null
      numeric_scale: null
      table: articles
    type: text
  - collection: articles
    field: date_created
    meta:
      collection: articles
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_created
      group: null
      hidden: false
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 8
      special:
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: datetime
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_created
      numeric_precision: null
      numeric_scale: null
      table: articles
    type: dateTime
  - collection: articles
    field: id
    meta:
      collection: articles
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: 1
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: char
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: false
      max_length: 36
      name: id
      numeric_precision: null
      numeric_scale: null
      table: articles
    type: uuid
  - collection: articles
    field: publish_date
    meta:
      collection: articles
      conditions: null
      display: datetime
      display_options:
        format: short
      field: publish_date
      group: null
      hidden: false
      interface: datetime
      note: null
      options: null
      readonly: false
      required: false
      sort: 3
      special: null
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: datetime
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: publish_date
      numeric_precision: null
      numeric_scale: null
      table: articles
    type: dateTime
  - collection: articles
    field: slug
    meta:
      collection: articles
      conditions: null
      display: null
      display_options: null
      field: slug
      group: null
      hidden: false
      interface: input
      note: null
      options:
        iconRight: insert_link
        placeholder: Enter a URL safe slug...
        slug: true
        trim: true
      readonly: false
      required: true
      sort: 7
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: varchar
      default_value: example-slug-here
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: true
      max_length: 255
      name: slug
      numeric_precision: null
      numeric_scale: null
      table: articles
    type: string
  - collection: articles
    field: status
    meta:
      collection: articles
      conditions: null
      display: labels
      display_options:
        choices:
          - text: $t:published
            value: published
            background: var(--primary)
            foreground: '#FFFFFF'
          - text: $t:draft
            value: draft
            background: '#D3DAE4'
            foreground: '#18222F'
          - text: $t:archived
            value: archived
            background: var(--warning)
            foreground: '#FFFFFF'
        showAsDot: true
      field: status
      group: null
      hidden: false
      interface: select-dropdown
      note: null
      options:
        choices:
          - text: $t:published
            value: published
          - text: $t:draft
            value: draft
          - text: $t:archived
            value: archived
      readonly: false
      required: false
      sort: 2
      special: null
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: varchar
      default_value: draft
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: status
      numeric_precision: null
      numeric_scale: null
      table: articles
    type: string
  - collection: articles
    field: summary
    meta:
      collection: articles
      conditions: null
      display: null
      display_options: null
      field: summary
      group: null
      hidden: false
      interface: input-multiline
      note: null
      options:
        placeholder: Enter a 1-2 sentence overview...
      readonly: false
      required: false
      sort: 5
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: text
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 65535
      name: summary
      numeric_precision: null
      numeric_scale: null
      table: articles
    type: text
  - collection: articles
    field: title
    meta:
      collection: articles
      conditions: null
      display: null
      display_options: null
      field: title
      group: null
      hidden: false
      interface: input
      note: null
      options:
        iconLeft: title
        trim: true
      readonly: false
      required: true
      sort: 4
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: varchar
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: title
      numeric_precision: null
      numeric_scale: null
      table: articles
    type: string
relations:
  - collection: articles
    field: author
    meta:
      junction_field: null
      many_collection: articles
      many_field: author
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_users
    schema:
      column: author
      constraint_name: articles_author_foreign
      foreign_key_column: id
      foreign_key_table: directus_users
      on_delete: NO ACTION
      on_update: NO ACTION
      table: articles
